# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import icons
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogAbout(object):
    def setupUi(self, dialogAbout):
        dialogAbout.setObjectName("dialogAbout")
        dialogAbout.resize(484, 435)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        dialogAbout.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogAbout.setWindowIcon(icon)
        dialogAbout.setStyleSheet("QDialog {\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(30, 33, 71, 255), stop:1 rgba(0, 0, 0, 255));\n"
                                  "}")
        dialogAbout.setLocale(QtCore.QLocale(
            QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.btnOk = QtWidgets.QPushButton(dialogAbout)
        self.btnOk.setGeometry(QtCore.QRect(150, 395, 180, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.btnOk.setFont(font)
        self.btnOk.setStyleSheet("QPushButton {\n"
                                 "    border: 0px solid ;\n"
                                 "    border-radius: 4px;\n"
                                 "    background-color: rgb(30, 31, 43);\n"
                                 "    color: rgb(203, 201, 205);\n"
                                 "}\n"
                                 "QPushButton:hover {\n"
                                 "    border: 0px solid ;\n"
                                 "    border-radius: 4px;\n"
                                 "    background-color: rgb(101, 54, 196);\n"
                                 "    color: #FFFFFF;\n"
                                 "}")
        self.btnOk.setObjectName("btnOk")
        self.label = QtWidgets.QLabel(dialogAbout)
        self.label.setGeometry(QtCore.QRect(18, 6, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #ffffff;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialogAbout)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #ffffff;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(dialogAbout)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 441, 91))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #ffffff;")
        self.label_3.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(dialogAbout)
        self.label_4.setGeometry(QtCore.QRect(20, 179, 441, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #FFFFFF;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(dialogAbout)
        self.label_5.setGeometry(QtCore.QRect(20, 204, 441, 171))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #FFFFFF;")
        self.label_5.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(dialogAbout)
        QtCore.QMetaObject.connectSlotsByName(dialogAbout)

    def retranslateUi(self, dialogAbout):
        _translate = QtCore.QCoreApplication.translate
        dialogAbout.setWindowTitle(_translate("dialogAbout", "Dialog"))
        self.btnOk.setText(_translate("dialogAbout", "Okey"))
        self.label.setText(_translate("dialogAbout", "SMW: Simple Patcher"))
        self.label_2.setText(_translate("dialogAbout", "By Propagandalf"))
        self.label_3.setText(_translate("dialogAbout", "<html><head/><body><p>This tool was designed to help people download and patch Super Mario World hacks really easy and fast. The ultimate goal is to hopefully bring more people in to the SMW hacking scene.<br/><br/>All content are imported from smwcentral.net. If you want to make your own hack, you can find all necessary tools and information on the site.</p></body></html>"))
        self.label_4.setText(_translate(
            "dialogAbout", "How do I use this application?"))
        self.label_5.setText(_translate("dialogAbout", "<html><head/><body><p>1. <span style=\" font-weight:400;\">Update the database.<br/></span>2.<span style=\" font-weight:400;\"> Download the Essential Files.<br/></span>3. <span style=\" font-weight:400;\">Select output folder. This is were the patched ROM(s) will be exported to.<br/></span>4. <span style=\" font-weight:400;\">Select a hack from the table and press &quot;Download And Patch ROM&quot;. You can alternatively select multiple hacks with the checkboxes and patch them all at once if you need to.</span></p><p><span style=\" font-weight:400;\">- You can search for any hack in the searchfield.<br/>- You can sort all hacks on the column names (date, exists, rating).<br/>- You can open the hacks website to read more about it.<br/>- Images, description &amp; authors is shown in the &quot;more info&quot;-section.<br/>- If you need to update the description/images to check for version changes, press the circular arrows button.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialogAbout = QtWidgets.QDialog()
    ui = Ui_dialogAbout()
    ui.setupUi(dialogAbout)
    dialogAbout.show()
    sys.exit(app.exec_())
