# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import icons
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 607)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(
            QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_top.setStyleSheet("QFrame{\n"
                                     "    background-color: #0F1015;\n"
                                     "    border: 0px;\n"
                                     "}")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnMoreInformation = QtWidgets.QPushButton(self.frame_top)
        self.btnMoreInformation.setMinimumSize(QtCore.QSize(0, 25))
        self.btnMoreInformation.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnMoreInformation.setFont(font)
        self.btnMoreInformation.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMoreInformation.setStyleSheet("QPushButton {\n"
                                              "    border: 0px solid ;\n"
                                              "    border-radius: 4px;\n"
                                              "    background-color: rgb(30, 31, 43);\n"
                                              "    min-height: 25px;\n"
                                              "    color: rgb(203, 201, 205);\n"
                                              "    padding-left: 10px;\n"
                                              "    padding-right: 10px;\n"
                                              "}\n"
                                              "QPushButton:hover {\n"
                                              "    border: 0px solid ;\n"
                                              "    border-radius: 4px;\n"
                                              "    background-color: rgb(101, 54, 196);\n"
                                              "    min-width: 80px;\n"
                                              "    max-width: 170px;\n"
                                              "    min-height: 25px;\n"
                                              "    color: #FFFFFF;\n"
                                              "}\n"
                                              "QPushButton::disabled {\n"
                                              "    border: 0px solid ;\n"
                                              "    border-radius: 4px;\n"
                                              "    background-color: rgb(19, 19, 21);\n"
                                              "    min-width: 80px;\n"
                                              "    max-width: 170px;\n"
                                              "    min-height: 25px;\n"
                                              "    color: rgb(56, 58, 62);\n"
                                              "}")
        self.btnMoreInformation.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/hamburger.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/img/hamburger_disabled.svg"),
                        QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btnMoreInformation.setIcon(icon1)
        self.btnMoreInformation.setObjectName("btnMoreInformation")
        self.horizontalLayout.addWidget(self.btnMoreInformation)
        self.btnUpdateDatabase = QtWidgets.QPushButton(self.frame_top)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnUpdateDatabase.setFont(font)
        self.btnUpdateDatabase.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnUpdateDatabase.setStyleSheet("QPushButton {\n"
                                             "    border: 0px solid ;\n"
                                             "    border-radius: 4px;\n"
                                             "    background-color: rgb(30, 31, 43);\n"
                                             "    min-width: 80px;\n"
                                             "    max-width: 170px;\n"
                                             "    min-height: 25px;\n"
                                             "    color: rgb(203, 201, 205);\n"
                                             "    padding-left: 10px;\n"
                                             "    padding-right: 10px;\n"
                                             "    margin-left: 10px;\n"
                                             "}\n"
                                             "QPushButton:hover {\n"
                                             "    border: 0px solid ;\n"
                                             "    border-radius: 4px;\n"
                                             "    background-color: rgb(101, 54, 196);\n"
                                             "    min-width: 80px;\n"
                                             "    max-width: 170px;\n"
                                             "    min-height: 25px;\n"
                                             "color: #FFFFFF;\n"
                                             "}\n"
                                             "QPushButton::disabled {\n"
                                             "    border: 0px solid ;\n"
                                             "    border-radius: 4px;\n"
                                             "    background-color: rgb(19, 19, 21);\n"
                                             "    min-width: 80px;\n"
                                             "    max-width: 170px;\n"
                                             "    min-height: 25px;\n"
                                             "    color: rgb(56, 58, 62);\n"
                                             "}")
        self.btnUpdateDatabase.setFlat(False)
        self.btnUpdateDatabase.setObjectName("btnUpdateDatabase")
        self.horizontalLayout.addWidget(self.btnUpdateDatabase)
        self.btnDownloadEssentialsFiles = QtWidgets.QPushButton(self.frame_top)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnDownloadEssentialsFiles.setFont(font)
        self.btnDownloadEssentialsFiles.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnDownloadEssentialsFiles.setStyleSheet("QPushButton {\n"
                                                      "    border: 0px solid ;\n"
                                                      "    border-radius: 4px;\n"
                                                      "    background-color: rgb(30, 31, 43);\n"
                                                      "    min-width: 80px;\n"
                                                      "    max-width: 170px;\n"
                                                      "    min-height: 25px;\n"
                                                      "    color: rgb(203, 201, 205);\n"
                                                      "    padding-left: 10px;\n"
                                                      "    padding-right: 10px;\n"
                                                      "    margin-left: 10px;\n"
                                                      "}\n"
                                                      "QPushButton:hover {\n"
                                                      "    border: 0px solid ;\n"
                                                      "    border-radius: 4px;\n"
                                                      "    background-color: rgb(101, 54, 196);\n"
                                                      "    min-width: 80px;\n"
                                                      "    max-width: 170px;\n"
                                                      "    min-height: 25px;\n"
                                                      "color: #FFFFFF;\n"
                                                      "}\n"
                                                      "QPushButton::disabled {\n"
                                                      "    border: 0px solid ;\n"
                                                      "    border-radius: 4px;\n"
                                                      "    background-color: rgb(19, 19, 21);\n"
                                                      "    min-width: 80px;\n"
                                                      "    max-width: 170px;\n"
                                                      "    min-height: 25px;\n"
                                                      "    color: rgb(56, 58, 62);\n"
                                                      "}")
        self.btnDownloadEssentialsFiles.setObjectName(
            "btnDownloadEssentialsFiles")
        self.horizontalLayout.addWidget(self.btnDownloadEssentialsFiles)
        self.btnSetOutputFolder = QtWidgets.QPushButton(self.frame_top)
        self.btnSetOutputFolder.setEnabled(True)
        self.btnSetOutputFolder.setMinimumSize(QtCore.QSize(160, 25))
        self.btnSetOutputFolder.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.btnSetOutputFolder.setFont(font)
        self.btnSetOutputFolder.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSetOutputFolder.setStyleSheet("QPushButton {\n"
                                              "    border: 0px solid ;\n"
                                              "    border-radius: 4px;\n"
                                              "    background-color: rgb(30, 31, 43);\n"
                                              "    min-height: 25px;\n"
                                              "    color: rgb(203, 201, 205);\n"
                                              "    margin-left: 10px;\n"
                                              "}\n"
                                              "QPushButton:hover {\n"
                                              "    border: 0px solid ;\n"
                                              "    border-radius: 4px;\n"
                                              "    background-color: rgb(101, 54, 196);\n"
                                              "    min-height: 25px;\n"
                                              "    color: #FFFFFF;\n"
                                              "}\n"
                                              "QPushButton::disabled {\n"
                                              "    border: 0px solid ;\n"
                                              "    border-radius: 4px;\n"
                                              "    background-color: rgb(19, 19, 21);\n"
                                              "    min-height: 25px;\n"
                                              "    color: rgb(56, 58, 62);\n"
                                              "}")
        self.btnSetOutputFolder.setIconSize(QtCore.QSize(15, 15))
        self.btnSetOutputFolder.setObjectName("btnSetOutputFolder")
        self.horizontalLayout.addWidget(self.btnSetOutputFolder)
        self.btnOpenRomFolder = QtWidgets.QPushButton(self.frame_top)
        self.btnOpenRomFolder.setStyleSheet("QPushButton {\n"
                                            "    border: 0px solid ;\n"
                                            "    border-radius: 4px;\n"
                                            "    background-color: rgb(30, 31, 43);\n"
                                            "    min-height: 25px;\n"
                                            "    min-width: 25px;\n"
                                            "    max-height: 25px;\n"
                                            "    max-width: 25px;\n"
                                            "    color: rgb(203, 201, 205);\n"
                                            "    margin-left: 10px;\n"
                                            "    margin-right: 10px;\n"
                                            "}\n"
                                            "QPushButton:hover {\n"
                                            "    border: 0px solid ;\n"
                                            "    border-radius: 4px;\n"
                                            "    background-color: rgb(101, 54, 196);\n"
                                            "    color: #FFFFFF;\n"
                                            "}\n"
                                            "QPushButton::disabled {\n"
                                            "    border: 0px solid ;\n"
                                            "    border-radius: 4px;\n"
                                            "    background-color: rgb(19, 19, 21);\n"
                                            "    color: rgb(56, 58, 62);\n"
                                            "}")
        self.btnOpenRomFolder.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/folder.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/img/folder_disabled.svg"),
                        QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btnOpenRomFolder.setIcon(icon2)
        self.btnOpenRomFolder.setObjectName("btnOpenRomFolder")
        self.horizontalLayout.addWidget(self.btnOpenRomFolder)
        self.labelSearch = QtWidgets.QLabel(self.frame_top)
        self.labelSearch.setEnabled(True)
        self.labelSearch.setMinimumSize(QtCore.QSize(25, 25))
        self.labelSearch.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.labelSearch.setFont(font)
        self.labelSearch.setStyleSheet("QLabel {\n"
                                       "    border: 0px solid ;\n"
                                       "    border-top-left-radius: 4px;\n"
                                       "    border-bottom-left-radius: 4px;\n"
                                       "    background-color: rgb(30, 31, 43);\n"
                                       "    color: rgb(203, 201, 205);\n"
                                       "    padding: 5px;\n"
                                       "}\n"
                                       "QLabel::disabled {\n"
                                       "    background-color: rgb(19, 19, 21);\n"
                                       "    color: rgb(56, 58, 62);\n"
                                       "}")
        self.labelSearch.setText("")
        self.labelSearch.setPixmap(
            QtGui.QPixmap(":/img/magnifier_disabled.svg"))
        self.labelSearch.setScaledContents(True)
        self.labelSearch.setObjectName("labelSearch")
        self.horizontalLayout.addWidget(self.labelSearch)
        self.inputSearch = QtWidgets.QPlainTextEdit(self.frame_top)
        self.inputSearch.setEnabled(True)
        self.inputSearch.setMinimumSize(QtCore.QSize(0, 25))
        self.inputSearch.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.inputSearch.setFont(font)
        self.inputSearch.setStyleSheet("QPlainTextEdit {\n"
                                       "    border: 0px solid ;\n"
                                       "    border-top-right-radius: 4px;\n"
                                       "    border-bottom-right-radius: 4px;\n"
                                       "    background-color: rgb(30, 31, 43);\n"
                                       "    color: rgb(203, 201, 205);\n"
                                       "    padding-top: 2px;\n"
                                       "}\n"
                                       "QPlainTextEdit::disabled {\n"
                                       "    background-color: rgb(19, 19, 21);\n"
                                       "    color: rgb(56, 58, 62);\n"
                                       "}")
        self.inputSearch.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inputSearch.setPlainText("")
        self.inputSearch.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.inputSearch.setObjectName("inputSearch")
        self.horizontalLayout.addWidget(self.inputSearch)
        self.btnDownloadRom = QtWidgets.QPushButton(self.frame_top)
        self.btnDownloadRom.setEnabled(True)
        self.btnDownloadRom.setMinimumSize(QtCore.QSize(0, 25))
        self.btnDownloadRom.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnDownloadRom.setFont(font)
        self.btnDownloadRom.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnDownloadRom.setStyleSheet("QPushButton {\n"
                                          "    border: 0px solid ;\n"
                                          "    border-radius: 4px;\n"
                                          "    background-color: rgb(30, 31, 43);\n"
                                          "    min-height: 25px;\n"
                                          "    color: rgb(203, 201, 205);\n"
                                          "    padding-left: 10px;\n"
                                          "    padding-right: 10px;\n"
                                          "    margin-left: 10px;\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "    border: 0px solid ;\n"
                                          "    border-radius: 4px;\n"
                                          "    background-color: rgb(101, 54, 196);\n"
                                          "    color: #FFFFFF;\n"
                                          "}\n"
                                          "QPushButton::disabled {\n"
                                          "    border: 0px solid ;\n"
                                          "    border-radius: 4px;\n"
                                          "    background-color: rgb(19, 19, 21);\n"
                                          "    color: rgb(56, 58, 62);\n"
                                          "}")
        self.btnDownloadRom.setObjectName("btnDownloadRom")
        self.horizontalLayout.addWidget(self.btnDownloadRom)
        self.btnGithub = QtWidgets.QPushButton(self.frame_top)
        self.btnGithub.setStyleSheet("QPushButton {\n"
                                     "    border: 0px solid ;\n"
                                     "    border-radius: 4px;\n"
                                     "    background-color: rgb(30, 31, 43);\n"
                                     "    min-height: 25px;\n"
                                     "    min-width: 25px;\n"
                                     "    max-height: 25px;\n"
                                     "    max-width: 25px;\n"
                                     "    color: rgb(203, 201, 205);\n"
                                     "    margin-left: 10px;\n"
                                     "}\n"
                                     "QPushButton:hover {\n"
                                     "    border: 0px solid ;\n"
                                     "    border-radius: 4px;\n"
                                     "    background-color: rgb(101, 54, 196);\n"
                                     "    color: #FFFFFF;\n"
                                     "}\n"
                                     "QPushButton::disabled {\n"
                                     "    border: 0px solid ;\n"
                                     "    border-radius: 4px;\n"
                                     "    background-color: rgb(19, 19, 21);\n"
                                     "    color: rgb(56, 58, 62);\n"
                                     "}")
        self.btnGithub.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/github.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/img/github_disabled.svg"),
                        QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btnGithub.setIcon(icon3)
        self.btnGithub.setObjectName("btnGithub")
        self.horizontalLayout.addWidget(self.btnGithub)
        self.btnHelp = QtWidgets.QPushButton(self.frame_top)
        self.btnHelp.setMinimumSize(QtCore.QSize(35, 25))
        self.btnHelp.setMaximumSize(QtCore.QSize(35, 25))
        self.btnHelp.setStyleSheet("QPushButton {\n"
                                   "    border: 0px solid ;\n"
                                   "    border-radius: 4px;\n"
                                   "    background-color: rgb(30, 31, 43);\n"
                                   "    min-height: 25px;\n"
                                   "    min-width: 25px;\n"
                                   "    max-height: 25px;\n"
                                   "    max-width: 25px;\n"
                                   "    color: rgb(203, 201, 205);\n"
                                   "    margin-left: 10px;\n"
                                   "}\n"
                                   "QPushButton:hover {\n"
                                   "    border: 0px solid ;\n"
                                   "    border-radius: 4px;\n"
                                   "    background-color: rgb(101, 54, 196);\n"
                                   "    color: #FFFFFF;\n"
                                   "}\n"
                                   "QPushButton::disabled {\n"
                                   "    border: 0px solid ;\n"
                                   "    border-radius: 4px;\n"
                                   "    background-color: rgb(19, 19, 21);\n"
                                   "    color: rgb(56, 58, 62);\n"
                                   "}")
        self.btnHelp.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/question.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/img/question_disabled.svg"),
                        QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btnHelp.setIcon(icon4)
        self.btnHelp.setIconSize(QtCore.QSize(13, 13))
        self.btnHelp.setObjectName("btnHelp")
        self.horizontalLayout.addWidget(self.btnHelp)
        self.verticalLayout_2.addWidget(self.frame_top)
        self.frame_content = QtWidgets.QFrame(self.centralwidget)
        self.frame_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_content)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_more_info = QtWidgets.QFrame(self.frame_content)
        self.frame_more_info.setMinimumSize(QtCore.QSize(332, 0))
        self.frame_more_info.setStyleSheet("QFrame {\n"
                                           "background-color: rgb(15, 16, 21);\n"
                                           "}")
        self.frame_more_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_more_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_more_info.setObjectName("frame_more_info")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_more_info)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_image = QtWidgets.QFrame(self.frame_more_info)
        self.frame_image.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_image.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_image.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_image.setObjectName("frame_image")
        self.btnNextImage = QtWidgets.QPushButton(self.frame_image)
        self.btnNextImage.setEnabled(False)
        self.btnNextImage.setGeometry(QtCore.QRect(293, 110, 31, 41))
        self.btnNextImage.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnNextImage.setStyleSheet("QPushButton {\n"
                                        "    border: 0px solid ;\n"
                                        "    border-radius: 4px;\n"
                                        "    background-color: rgb(30, 31, 43);\n"
                                        "    color: rgb(203, 201, 205);\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    border: 0px solid ;\n"
                                        "    border-radius: 4px;\n"
                                        "    background-color: rgb(101, 54, 196);\n"
                                        "    color: #FFFFFF;\n"
                                        "}\n"
                                        "QPushButton::disabled {\n"
                                        "    border: 0px solid ;\n"
                                        "    border-radius: 4px;\n"
                                        "    background-color: rgb(19, 19, 21);\n"
                                        "    color: rgb(56, 58, 62);\n"
                                        "}")
        self.btnNextImage.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/next.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/img/next_disabled.svg"),
                        QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btnNextImage.setIcon(icon5)
        self.btnNextImage.setObjectName("btnNextImage")
        self.btnPreviousImage = QtWidgets.QPushButton(self.frame_image)
        self.btnPreviousImage.setEnabled(False)
        self.btnPreviousImage.setGeometry(QtCore.QRect(8, 110, 31, 41))
        self.btnPreviousImage.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPreviousImage.setStyleSheet("QPushButton {\n"
                                            "    border: 0px solid ;\n"
                                            "    border-radius: 4px;\n"
                                            "    background-color: rgb(30, 31, 43);\n"
                                            "    color: rgb(203, 201, 205);\n"
                                            "}\n"
                                            "QPushButton:hover {\n"
                                            "    border: 0px solid ;\n"
                                            "    border-radius: 4px;\n"
                                            "    background-color: rgb(101, 54, 196);\n"
                                            "    color: #FFFFFF;\n"
                                            "}\n"
                                            "QPushButton::disabled {\n"
                                            "    border: 0px solid ;\n"
                                            "    border-radius: 4px;\n"
                                            "    background-color: rgb(19, 19, 21);\n"
                                            "    color: rgb(56, 58, 62);\n"
                                            "}")
        self.btnPreviousImage.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/previous.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/img/previous_disabled.svg"),
                        QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btnPreviousImage.setIcon(icon6)
        self.btnPreviousImage.setObjectName("btnPreviousImage")
        self.labelGameImage = QtWidgets.QLabel(self.frame_image)
        self.labelGameImage.setEnabled(False)
        self.labelGameImage.setGeometry(QtCore.QRect(46, 17, 240, 226))
        self.labelGameImage.setMinimumSize(QtCore.QSize(240, 226))
        self.labelGameImage.setMaximumSize(QtCore.QSize(240, 226))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.labelGameImage.setFont(font)
        self.labelGameImage.setStyleSheet("QLabel {\n"
                                          "    border: 3px solid;\n"
                                          "    border-color: rgb(30, 31, 43);\n"
                                          "    background-color: rgb(30, 31, 43);\n"
                                          "    color: rgb(203, 201, 205);\n"
                                          "}\n"
                                          "QLabel::disabled {\n"
                                          "    border-color: rgb(19, 19, 21);\n"
                                          "    background-color: rgb(19, 19, 21);\n"
                                          "    color: rgb(56, 58, 62);\n"
                                          "}")
        self.labelGameImage.setTextFormat(QtCore.Qt.PlainText)
        self.labelGameImage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGameImage.setObjectName("labelGameImage")
        self.verticalLayout.addWidget(self.frame_image)
        self.frame_text = QtWidgets.QFrame(self.frame_more_info)
        self.frame_text.setStyleSheet("QScrollBar:vertical\n"
                                      " {\n"
                                      "     background-color: #2A2929;\n"
                                      "     width: 20px;\n"
                                      "     margin: 5px 5px 5px 5px;\n"
                                      "     border: 1px transparent #2A2929;\n"
                                      "     border-radius: 4px;\n"
                                      " }\n"
                                      "\n"
                                      " QScrollBar::handle:vertical\n"
                                      " {\n"
                                      "     background-color: rgb(101, 54, 196);\n"
                                      "     min-height: 30px;\n"
                                      "     border-radius: 4px;\n"
                                      " }\n"
                                      "\n"
                                      " QScrollBar::sub-line:vertical\n"
                                      " {\n"
                                      "     margin: 3px 0px 3px 0px;\n"
                                      "     border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
                                      "     height: 10px;\n"
                                      "     width: 10px;\n"
                                      "     subcontrol-position: top;\n"
                                      "     subcontrol-origin: margin;\n"
                                      " }\n"
                                      "\n"
                                      " QScrollBar::add-line:vertical\n"
                                      " {\n"
                                      "     margin: 3px 0px 3px 0px;\n"
                                      "     border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
                                      "     height: 10px;\n"
                                      "     width: 10px;\n"
                                      "     subcontrol-position: bottom;\n"
                                      "     subcontrol-origin: margin;\n"
                                      " }\n"
                                      "\n"
                                      " QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
                                      " {\n"
                                      "\n"
                                      "     border-image: url(:/qss_icons/rc/up_arrow.png);\n"
                                      "     height: 10px;\n"
                                      "     width: 10px;\n"
                                      "     subcontrol-position: top;\n"
                                      "     subcontrol-origin: margin;\n"
                                      " }\n"
                                      "\n"
                                      "\n"
                                      " QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
                                      " {\n"
                                      "     border-image: url(:/qss_icons/rc/down_arrow.png);\n"
                                      "     height: 10px;\n"
                                      "     width: 10px;\n"
                                      "     subcontrol-position: bottom;\n"
                                      "     subcontrol-origin: margin;\n"
                                      " }\n"
                                      "\n"
                                      " QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
                                      " {\n"
                                      "     background: none;\n"
                                      " }\n"
                                      "\n"
                                      "\n"
                                      " QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
                                      " {\n"
                                      "     background: none;\n"
                                      " }")
        self.frame_text.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_text.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_text.setObjectName("frame_text")
        self.labelAuthorsHeader = QtWidgets.QLabel(self.frame_text)
        self.labelAuthorsHeader.setEnabled(False)
        self.labelAuthorsHeader.setGeometry(QtCore.QRect(10, 223, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.labelAuthorsHeader.setFont(font)
        self.labelAuthorsHeader.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelAuthorsHeader.setStyleSheet("QLabel {\n"
                                              "    color: #ffffff;\n"
                                              "    border: 0px solid ;\n"
                                              "    border-radius: 4px;\n"
                                              "    background-color: rgb(30, 31, 43);\n"
                                              "    min-height: 25px;\n"
                                              "    color: rgb(203, 201, 205);\n"
                                              "}\n"
                                              "QLabel::disabled {\n"
                                              "    background-color: rgb(19, 19, 21);\n"
                                              "    color: rgb(56, 58, 62);\n"
                                              "}")
        self.labelAuthorsHeader.setObjectName("labelAuthorsHeader")
        self.textDescription = QtWidgets.QTextBrowser(self.frame_text)
        self.textDescription.setEnabled(True)
        self.textDescription.setGeometry(QtCore.QRect(6, 22, 321, 185))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.textDescription.setFont(font)
        self.textDescription.setStyleSheet("QTextBrowser {\n"
                                           "    color: #ffffff;\n"
                                           "}\n"
                                           "QTextBrowser::disabled {\n"
                                           "    color: rgb(56, 58, 62);\n"
                                           "}")
        self.textDescription.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textDescription.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded)
        self.textDescription.setAcceptRichText(False)
        self.textDescription.setOpenLinks(False)
        self.textDescription.setObjectName("textDescription")
        self.btnVisitWebsite = QtWidgets.QPushButton(self.frame_text)
        self.btnVisitWebsite.setEnabled(False)
        self.btnVisitWebsite.setGeometry(QtCore.QRect(298, 255, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.btnVisitWebsite.setFont(font)
        self.btnVisitWebsite.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnVisitWebsite.setStyleSheet("QPushButton {\n"
                                           "    border: 0px solid ;\n"
                                           "    border-radius: 4px;\n"
                                           "    background-color: rgb(30, 31, 43);\n"
                                           "    min-height: 25px;\n"
                                           "    color: rgb(203, 201, 205);\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    border: 0px solid ;\n"
                                           "    border-radius: 4px;\n"
                                           "    background-color: rgb(101, 54, 196);\n"
                                           "    color: #FFFFFF;\n"
                                           "}\n"
                                           "QPushButton::disabled {\n"
                                           "    border: 0px solid ;\n"
                                           "    border-radius: 4px;\n"
                                           "    background-color: rgb(19, 19, 21);\n"
                                           "    color: rgb(56, 58, 62);\n"
                                           "}")
        self.btnVisitWebsite.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/openbrowser.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/img/openbrowser_disabled.svg"),
                        QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btnVisitWebsite.setIcon(icon7)
        self.btnVisitWebsite.setIconSize(QtCore.QSize(14, 14))
        self.btnVisitWebsite.setObjectName("btnVisitWebsite")
        self.btnSidebarDownload = QtWidgets.QPushButton(self.frame_text)
        self.btnSidebarDownload.setEnabled(False)
        self.btnSidebarDownload.setGeometry(QtCore.QRect(10, 255, 181, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.btnSidebarDownload.setFont(font)
        self.btnSidebarDownload.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSidebarDownload.setStyleSheet("QPushButton {\n"
                                              "    border: 0px solid ;\n"
                                              "    border-radius: 4px;\n"
                                              "    background-color: rgb(30, 31, 43);\n"
                                              "    min-height: 25px;\n"
                                              "    color: rgb(203, 201, 205);\n"
                                              "}\n"
                                              "QPushButton:hover {\n"
                                              "    border: 0px solid ;\n"
                                              "    border-radius: 4px;\n"
                                              "    background-color: rgb(101, 54, 196);\n"
                                              "    color: #FFFFFF;\n"
                                              "}\n"
                                              "QPushButton::disabled {\n"
                                              "    border: 0px solid ;\n"
                                              "    border-radius: 4px;\n"
                                              "    background-color: rgb(19, 19, 21);\n"
                                              "    color: rgb(56, 58, 62);\n"
                                              "}")
        self.btnSidebarDownload.setObjectName("btnSidebarDownload")
        self.labelAuthors = QtWidgets.QLabel(self.frame_text)
        self.labelAuthors.setGeometry(QtCore.QRect(88, 225, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.labelAuthors.setFont(font)
        self.labelAuthors.setStyleSheet("QLabel {\n"
                                        "color: #ffffff;\n"
                                        "}\n"
                                        "QLabel::disabled {\n"
                                        "    color: rgb(56, 58, 62);\n"
                                        "}")
        self.labelAuthors.setText("")
        self.labelAuthors.setObjectName("labelAuthors")
        self.btnOpenZip = QtWidgets.QPushButton(self.frame_text)
        self.btnOpenZip.setEnabled(False)
        self.btnOpenZip.setGeometry(QtCore.QRect(264, 255, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.btnOpenZip.setFont(font)
        self.btnOpenZip.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnOpenZip.setStyleSheet("QPushButton {\n"
                                      "    border: 0px solid ;\n"
                                      "    border-radius: 4px;\n"
                                      "    background-color: rgb(30, 31, 43);\n"
                                      "    min-height: 25px;\n"
                                      "    color: rgb(203, 201, 205);\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    border: 0px solid ;\n"
                                      "    border-radius: 4px;\n"
                                      "    background-color: rgb(101, 54, 196);\n"
                                      "    color: #FFFFFF;\n"
                                      "}\n"
                                      "QPushButton::disabled {\n"
                                      "    border: 0px solid ;\n"
                                      "    border-radius: 4px;\n"
                                      "    background-color: rgb(19, 19, 21);\n"
                                      "    color: rgb(56, 58, 62);\n"
                                      "}")
        self.btnOpenZip.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/zip.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/img/zip_disabled.svg"),
                        QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btnOpenZip.setIcon(icon8)
        self.btnOpenZip.setIconSize(QtCore.QSize(14, 14))
        self.btnOpenZip.setObjectName("btnOpenZip")
        self.btnUpdateInfo = QtWidgets.QPushButton(self.frame_text)
        self.btnUpdateInfo.setEnabled(False)
        self.btnUpdateInfo.setGeometry(QtCore.QRect(199, 255, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.btnUpdateInfo.setFont(font)
        self.btnUpdateInfo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnUpdateInfo.setStyleSheet("QPushButton {\n"
                                         "    border: 0px solid ;\n"
                                         "    border-radius: 4px;\n"
                                         "    background-color: rgb(30, 31, 43);\n"
                                         "    min-height: 25px;\n"
                                         "    color: rgb(203, 201, 205);\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    border: 0px solid ;\n"
                                         "    border-radius: 4px;\n"
                                         "    background-color: rgb(101, 54, 196);\n"
                                         "    color: #FFFFFF;\n"
                                         "}\n"
                                         "QPushButton::disabled {\n"
                                         "    border: 0px solid ;\n"
                                         "    border-radius: 4px;\n"
                                         "    background-color: rgb(19, 19, 21);\n"
                                         "    color: rgb(56, 58, 62);\n"
                                         "}")
        self.btnUpdateInfo.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img/update.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/img/update_disabled.svg"),
                        QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btnUpdateInfo.setIcon(icon9)
        self.btnUpdateInfo.setIconSize(QtCore.QSize(14, 14))
        self.btnUpdateInfo.setObjectName("btnUpdateInfo")
        self.labelGameName = QtWidgets.QLabel(self.frame_text)
        self.labelGameName.setGeometry(QtCore.QRect(10, 0, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.labelGameName.setFont(font)
        self.labelGameName.setStyleSheet("QLabel {\n"
                                         "    color: #ffffff;\n"
                                         "}\n"
                                         "QLabel::disabled {\n"
                                         "    color: rgb(56, 58, 62);\n"
                                         "}")
        self.labelGameName.setText("")
        self.labelGameName.setObjectName("labelGameName")
        self.labelImageNumber = QtWidgets.QLabel(self.frame_text)
        self.labelImageNumber.setGeometry(QtCore.QRect(276, 0, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.labelImageNumber.setFont(font)
        self.labelImageNumber.setStyleSheet("QLabel {\n"
                                            "    color: #ffffff;\n"
                                            "}\n"
                                            "QLabel::disabled {\n"
                                            "    color: rgb(56, 58, 62);\n"
                                            "}")
        self.labelImageNumber.setText("")
        self.labelImageNumber.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.labelImageNumber.setObjectName("labelImageNumber")
        self.verticalLayout.addWidget(self.frame_text)
        self.horizontalLayout_3.addWidget(self.frame_more_info)
        self.table = QtWidgets.QFrame(self.frame_content)
        self.table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.table.setFrameShadow(QtWidgets.QFrame.Raised)
        self.table.setObjectName("table")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.table)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.table)
        self.tableWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("QTableWidget{\n"
                                       "background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(30, 33, 71, 255), stop:1 rgba(0, 0, 0, 255));\n"
                                       "color: rgb(247, 245, 249);\n"
                                       "}\n"
                                       "QTableWidget::disabled{\n"
                                       "    color: rgb(56, 58, 62);\n"
                                       "}\n"
                                       "QTableWidget::item:selected{\n"
                                       "background-color: rgb(101, 54, 196);\n"
                                       "color: #FFFFFF;\n"
                                       "}\n"
                                       "QHeaderView::section { \n"
                                       "    color:white;\n"
                                       "    background-color:rgb(28, 30, 40);\n"
                                       "    font-weight: bold;\n"
                                       "    border: 0px solid;\n"
                                       "}\n"
                                       "QHeaderView {\n"
                                       " background-color:rgb(28, 30, 40);\n"
                                       "}\n"
                                       " QScrollBar:vertical\n"
                                       " {\n"
                                       "     background-color: #2A2929;\n"
                                       "     width: 20px;\n"
                                       "     margin: 5px 5px 5px 5px;\n"
                                       "     border: 1px transparent #2A2929;\n"
                                       "     border-radius: 4px;\n"
                                       " }\n"
                                       " QScrollBar::handle:vertical\n"
                                       " {\n"
                                       "     background-color: rgb(101, 54, 196);\n"
                                       "     min-height: 30px;\n"
                                       "     border-radius: 4px;\n"
                                       " }\n"
                                       " QScrollBar::sub-line:vertical\n"
                                       " {\n"
                                       "     margin: 3px 0px 3px 0px;\n"
                                       "     border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
                                       "     height: 10px;\n"
                                       "     width: 10px;\n"
                                       "     subcontrol-position: top;\n"
                                       "     subcontrol-origin: margin;\n"
                                       " }\n"
                                       " QScrollBar::add-line:vertical\n"
                                       " {\n"
                                       "     margin: 3px 0px 3px 0px;\n"
                                       "     border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
                                       "     height: 10px;\n"
                                       "     width: 10px;\n"
                                       "     subcontrol-position: bottom;\n"
                                       "     subcontrol-origin: margin;\n"
                                       " }\n"
                                       " QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
                                       " {\n"
                                       "     border-image: url(:/qss_icons/rc/up_arrow.png);\n"
                                       "     height: 10px;\n"
                                       "     width: 10px;\n"
                                       "     subcontrol-position: top;\n"
                                       "     subcontrol-origin: margin;\n"
                                       " }\n"
                                       " QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
                                       " {\n"
                                       "     border-image: url(:/qss_icons/rc/down_arrow.png);\n"
                                       "     height: 10px;\n"
                                       "     width: 10px;\n"
                                       "     subcontrol-position: bottom;\n"
                                       "     subcontrol-origin: margin;\n"
                                       " }\n"
                                       " QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
                                       " {\n"
                                       "     background: none;\n"
                                       " }\n"
                                       " QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
                                       " {\n"
                                       "     background: none;\n"
                                       " }\n"
                                       "QTableView::indicator:unchecked {\n"
                                       "    background-color: #0F1015;\n"
                                       "    border: 1px solid;\n"
                                       "    border-color: rgb(30, 31, 43);\n"
                                       "}\n"
                                       "QTableView::indicator:checked {\n"
                                       "    background-color:  rgb(101, 54, 196);\n"
                                       "}\n"
                                       "")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(0)
        self.tableWidget.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(
            QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(15)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout_4.addWidget(self.tableWidget)
        self.horizontalLayout_3.addWidget(self.table)
        self.verticalLayout_2.addWidget(self.frame_content)
        self.frame_bottom = QtWidgets.QFrame(self.centralwidget)
        self.frame_bottom.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_bottom.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_bottom.setStyleSheet("QFrame{\n"
                                        "background-color: #0F1015;\n"
                                        "border: 0px;\n"
                                        "}")
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_bottom)
        self.horizontalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.frame_bottom)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 8))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 8))
        self.progressBar.setStyleSheet("QProgressBar\n"
                                       "{\n"
                                       "    background-color: #212529;\n"
                                       "    border: 0px solid;\n"
                                       "    border-radius: 4px;\n"
                                       "}\n"
                                       "QProgressBar::chunk \n"
                                       "{\n"
                                       "    border: solid grey;\n"
                                       "    background-color: rgb(85, 255, 0);\n"
                                       "}   ")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.label = QtWidgets.QLabel(self.frame_bottom)
        self.label.setMinimumSize(QtCore.QSize(300, 0))
        self.label.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
                                 "margin-left: 10px;\n"
                                 "color: #FFFFFF;\n"
                                 "}")
        self.label.setAlignment(QtCore.Qt.AlignLeading |
                                QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_bottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "SMW: Simple Patcher"))
        self.btnUpdateDatabase.setText(
            _translate("MainWindow", "Update Database"))
        self.btnDownloadEssentialsFiles.setText(
            _translate("MainWindow", "Download Essential Files"))
        self.btnSetOutputFolder.setText(
            _translate("MainWindow", "Select Output Folder"))
        self.btnDownloadRom.setText(_translate(
            "MainWindow", "Download selected ROMs"))
        self.labelGameImage.setText(_translate(
            "MainWindow", "You need to select a game..."))
        self.labelAuthorsHeader.setText(_translate("MainWindow", "  Authors:"))
        self.textDescription.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'Verdana\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btnSidebarDownload.setText(_translate(
            "MainWindow", "Download and Patch ROM"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Exit(s)"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Rating"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Trusted"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "DLs"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Updated"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Demo"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Featured"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Authors"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Size"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Link"))
        self.label.setText(_translate(
            "MainWindow", "SWM: Simple Patcher - by Propagandalf"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
